language: python
python: "2.7"
install:
  - pip install ansible
script:
  - ansible-playbook --syntax-check -i production site.yml
  - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i production site.yml
