"""empty message

Revision ID: faa87b27e92
Revises: 4e2935313eda
Create Date: 2015-05-06 22:49:36.271855

"""

# revision identifiers, used by Alembic.
revision = 'faa87b27e92'
down_revision = '4e2935313eda'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selfies', sa.Column('picture', sa.Text(), nullable=False))
    op.add_column('selfies', sa.Column('qid', sa.Integer(), nullable=False))
    op.drop_column('selfies', 'proposal_id')
    op.drop_column('selfies', 'outcome_id')
    op.drop_column('selfies', 'created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selfies', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('selfies', sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('selfies', sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('selfies', 'qid')
    op.drop_column('selfies', 'picture')
