---

- name: Install Postgres
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-9.3

- name: Set postgres password
  command: sudo -u {{ db_admin_username }} psql -d {{ db_admin_username }} -c "ALTER USER postgres with  password '{{ db_admin_password }}';"

- name: Create postgres configuration file
  template:
    src: postgresql.conf
    dest: /etc/postgresql/9.3/main/postgresql.conf
    group: postgres
    owner: postgres
    mode: 0640
  register: postgres_conf

- name: Create postgres hba conf
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    group: postgres
    owner: postgres
    mode: 0640
  register: postgres_conf

- name: Restart Postgres
  service:
    name: postgresql
    state: restarted
  when: postgres_conf.changed postgres_hba.changed

- name: Set firewall rules for postgres
  ufw: rule=allow port=5432 proto=tcp
