---
galaxy_info:
  author: Brian Akins
  description: Runit
  license: Apache2
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - lucid
    - maverick
    - natty
    - oneiric
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
    - system
dependencies: []
