---

- name: app | Set firewall rules for web traffic
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https

- name: app | install dependencies
  file: src=/vagrant/src/app dest=/opt/app state=link
  when: ansible_env == 'dev'

- name: app | create app group
  group: name=app state=present system=yes

- name: app | create app user
  user: name=app group=app createhome=no shell=/bin/false system=yes state=present

- name: app | create service
  template: src=service.conf.j2 dest=/etc/init/app.conf backup=yes mode=0644

- name: app | start service
  service: name=app state=started enabled=yes
