---

- name: api | Set firewall rules for web traffic
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https

- name: api | install package dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - libpq-dev
    - python-dev
    - libffi-dev

- name: api | install source tree
  file: src=/vagrant/src/api dest=/opt/api state=link
  when: ansible_env == 'dev'

- name: api | create group
  group: name=api state=present system=yes

- name: api | create user
  user: name=api group=api createhome=no shell=/bin/false system=yes state=present

- name: api | install config file
  template: src=config.yaml.j2 dest=/opt/api/config.yaml

- name: api | create service
  template: src=service.conf.j2 dest=/etc/init/api.conf backup=yes mode=0644

- name: api | start service
  service: name=api state=started enabled=yes
